/**
 * cards.js — pure content.
 *
 * DESIGN RULE: randomness lives only in WHICH eligible card is drawn.
 * Accepting a card never rolls dice. The only hidden rolls in the game are
 * declared up front by the fiction: a manager's honesty (set at signing,
 * revealed years later), award wins, and certification levels.
 *
 * SCHEMA
 *   id       unique
 *   cls      'COMMON' | 'CONTRACT' | 'RARE' | 'WHALE'
 *   title    short, no punctuation
 *   cast     { tier: 1..5 } | { track: 'underground' } | { track: 'director' } | null
 *            -> injects {artist} into body/diary from roster.js
 *   req      gating. scalar = minimum, [a,b] = inclusive range.
 *            keys: skill taste relevance connections cash age status
 *                  flags (all required) not (none may be present)
 *                  region (cast must be from this territory)
 *   weight   draw weight within its class (default 1)
 *   accept / pass:
 *            label   button text
 *            fx      effects object, or (s) => effects object
 *            diary   string (tokens {artist} {age}) or null to fall through
 *
 * EFFECT KEYS
 *   skill taste relevance connections cash publishing
 *   placement: { tier }        records a credit with the cast artist
 *   underground: true          marks the placement as underground-track
 *   score: true                the placement is a score (Oscar/Emmy eligible)
 *   tv: true                   the placement is television (Emmy eligible)
 *   flags: []                  set run flags
 *   clearFlags: []
 *   royaltyMult                multiplies future royalty income (0.5 = gave up points)
 */

export const CARDS = [
  /* ================================================================= */
  /* COMMON — service work, small placements, gear, people who flake   */
  /* ================================================================= */
  {
    id: 'c_group_chat_beat',
    cls: 'COMMON',
    title: 'Sixty dollars',
    cast: { tier: 1 },
    req: { age: [14, 24] },
    weight: 3,
    body: (v) => `${v.artist} heard your beat in a group chat and wants it for a mixtape nobody will hear. There is sixty dollars in it.`,
    accept: {
      label: 'Sell it',
      fx: { cash: 60, relevance: 3, connections: 2, skill: 1, placement: { tier: 1 }, flags: ['early_collab'] },
      diary: 'you sold your first beat to {artist} for sixty dollars and did not sleep that night.',
    },
    pass: { label: 'Keep it', fx: { taste: 2 }, diary: 'you turned down sixty dollars because the beat was not finished. It never got finished.' },
  },
  {
    id: 'c_talent_show',
    cls: 'COMMON',
    title: 'The talent show',
    req: { age: [14, 18] },
    body: () => 'The school wants someone to run sound for the spring showcase. It is four evenings and no money.',
    accept: { label: 'Run sound', fx: { skill: 4, connections: 3 }, diary: 'you ran sound for the spring showcase and learned more in four nights than in six months of tutorials.' },
    pass: { label: 'Stay in the basement', fx: { skill: 3, relevance: -1 }, diary: null },
  },
  {
    id: 'c_cracked_plugin',
    cls: 'COMMON',
    title: 'The torrent',
    req: { age: [14, 22] },
    body: () => 'Somebody posts a working crack of the $2,000 bundle. Your machine already runs hot.',
    accept: { label: 'Install it', fx: { skill: 6, taste: -1 }, diary: 'you installed the whole cracked bundle and the laptop never really recovered.' },
    pass: { label: 'Use the stock plugins', fx: { skill: 3, taste: 3 }, diary: 'you learned the stock compressor instead. It made you better than the people with everything.' },
  },
  {
    id: 'c_older_producer',
    cls: 'COMMON',
    title: 'Somebody older',
    req: { age: [14, 26], connections: 5 },
    weight: 2,
    body: () => 'A producer twelve years older offers to listen to four of your beats and tell you the truth about them.',
    accept: { label: 'Play him the four', fx: { skill: 5, taste: 4, connections: 4 }, diary: 'he told you the truth about four of your beats and you were quiet on the drive home.' },
    pass: { label: 'Not yet', fx: { relevance: 1 }, diary: null },
  },
  {
    id: 'c_type_beats',
    cls: 'COMMON',
    title: 'Type beats',
    req: { age: [16, 30], skill: 15 },
    weight: 3,
    body: () => 'You could upload forty type beats a month. It is not what you want to make. It is a hundred dollars a week.',
    accept: { label: 'Upload them', fx: { cash: 5200, relevance: 4, taste: -5, skill: 3 }, diary: 'you uploaded forty type beats a month for two years and got very fast at sounding like other people.' },
    pass: { label: 'Refuse', fx: { taste: 3, cash: -200 }, diary: null },
  },
  {
    id: 'c_open_mic',
    cls: 'COMMON',
    title: 'The open mic',
    cast: { tier: 1 },
    req: { age: [15, 26] },
    weight: 2,
    body: (v) => `${v.artist} needs beats for a set at the open mic on Thursday. There is no money and the room holds forty people.`,
    accept: { label: 'Do it', fx: { relevance: 4, connections: 5, placement: { tier: 1 } }, diary: 'forty people heard it in a room above a bar and eleven of them looked up.' },
    pass: { label: 'Skip it', fx: { skill: 2 }, diary: null },
  },
  {
    id: 'c_interface_dies',
    cls: 'COMMON',
    title: 'The interface dies',
    req: { age: [15, 30] },
    body: () => 'The interface stops passing audio in the middle of a session. A used replacement is $340 you do not really have.',
    accept: { label: 'Buy the replacement', fx: { cash: -340, skill: 2 }, diary: 'you bought the used interface off a guy in a parking lot and it worked for nine years.' },
    pass: { label: 'Work around it', fx: { skill: 3, taste: 1 }, diary: 'you spent four months recording everything through a headphone jack and somehow it sounded fine.' },
  },
  {
    id: 'c_college',
    cls: 'COMMON',
    title: 'The application',
    req: { age: [17, 20] },
    weight: 3,
    body: () => 'There is a music program four states away. Real rooms, real faculty, forty thousand dollars a year of somebody\'s money.',
    accept: { label: 'Go', fx: { skill: 12, taste: 8, connections: 8, cash: -22000, relevance: -6 }, diary: 'you went. Four years of real rooms and a debt you would carry into your thirties.' },
    pass: { label: 'Stay home', fx: { skill: 5, relevance: 4, cash: 2000 }, diary: "you told your mother you weren't going to apply anywhere." },
  },
  {
    id: 'c_move_to_city',
    cls: 'COMMON',
    title: 'The lease',
    req: { age: [18, 30], not: ['moved'] },
    weight: 3,
    body: () => 'A room in a three-bedroom, in a city where this job actually exists. First, last, and a deposit.',
    accept: { label: 'Sign the lease', fx: { cash: -6500, relevance: 8, connections: 12, flags: ['moved'] }, diary: 'you moved with two bags and a monitor under your arm and knew nobody.' },
    pass: { label: 'Stay put', fx: { cash: 1500, skill: 4, relevance: -3 }, diary: 'you stayed. The rent was nothing and so was everything else.' },
  },
  {
    id: 'c_engineer_gig',
    cls: 'COMMON',
    title: 'Nights at the studio',
    req: { age: [18, 32], skill: 25 },
    weight: 2,
    body: () => 'The commercial room needs a night engineer. Midnight to eight, other people\'s sessions, every night.',
    accept: { label: 'Take the shifts', fx: { cash: 26000, skill: 10, connections: 14 }, diary: 'you engineered other people\'s sessions from midnight to eight and learned the whole business sideways.' },
    pass: { label: 'Decline', fx: {}, diary: null },
  },
  {
    id: 'c_ghost_mixes',
    cls: 'COMMON',
    title: 'Mixes, uncredited',
    req: { age: [20, 46], skill: 35 },
    weight: 3,
    body: () => 'A working producer wants you to mix his queue. Good money, fast turnaround, your name nowhere on it.',
    accept: { label: 'Mix them', fx: (s) => ({ cash: 900 * Math.max(10, s.skill), skill: 5, relevance: -3, connections: 6 }), diary: 'you mixed forty records that year and are credited on none of them.' },
    pass: { label: 'Only with credit', fx: { taste: 3, relevance: 1 }, diary: null },
  },
  {
    id: 'c_rising_single',
    cls: 'COMMON',
    title: 'A little heat',
    cast: { tier: 2 },
    req: { skill: 26, relevance: 8 },
    weight: 4,
    body: (v) => `${v.artist} has a little heat and no producer. The single is yours if you can turn it in three weeks.`,
    accept: { label: 'Take the single', fx: { placement: { tier: 2 }, relevance: 8, connections: 5, cash: 4500, skill: 2 }, diary: 'you produced {artist}\'s single and heard it in a car that was not yours.' },
    pass: { label: 'Pass', fx: { taste: 1 }, diary: null },
  },
  {
    id: 'c_b_side',
    cls: 'COMMON',
    title: 'The B-side',
    cast: { tier: 3 },
    req: { skill: 45, connections: 25, relevance: 25 },
    weight: 3,
    body: (v) => `${v.artist}'s album has a hole at track nine. It will not be the single. It will be on the album.`,
    accept: { label: 'Fill track nine', fx: { placement: { tier: 3 }, relevance: 9, cash: 12000, taste: 2, connections: 4 }, diary: 'track nine on {artist}\'s album was yours. Track nine is where the good ones hide.' },
    pass: { label: 'Hold out for a single', fx: { relevance: -2 }, diary: null },
  },
  {
    id: 'c_playlist_editor',
    cls: 'COMMON',
    title: 'The editor',
    req: { relevance: 16, connections: 16 },
    weight: 2,
    body: () => 'A playlist editor will take your calls if you take her calls. That is the whole arrangement and it is worth a great deal.',
    accept: { label: 'Take the arrangement', fx: { relevance: 12, connections: 8, taste: -4 }, diary: 'you learned exactly what the algorithm wanted and gave it to her on a schedule.' },
    pass: { label: 'Decline politely', fx: { taste: 4, relevance: -2 }, diary: null },
  },
  {
    id: 'c_writing_camp',
    cls: 'COMMON',
    title: 'The camp',
    req: { skill: 40, connections: 30, age: [21, 44] },
    weight: 3,
    body: () => 'Nine days, six rooms, thirty writers, one artist who may or may not show up. You will make forty songs and place none of them, or one.',
    accept: { label: 'Go to camp', fx: { connections: 14, skill: 4, relevance: 5, taste: -2 }, diary: 'nine days, six rooms, forty songs. One of them went somewhere and it was not the one you liked.' },
    pass: { label: 'Stay home and work', fx: { skill: 5, taste: 3 }, diary: null },
  },
  {
    id: 'c_remix',
    cls: 'COMMON',
    title: 'The remix',
    cast: { tier: 3 },
    req: { skill: 40, relevance: 22 },
    weight: 3,
    body: (v) => `${v.artist}'s label wants an official remix. Flat fee, no points, delivered Friday.`,
    accept: { label: 'Deliver Friday', fx: { cash: 9000, relevance: 7, connections: 3 }, diary: 'you did the remix in a weekend and it outperformed the original, which nobody mentioned again.' },
    pass: { label: 'No points, no thanks', fx: { taste: 2 }, diary: null },
  },
  {
    id: 'c_tour_md',
    cls: 'COMMON',
    title: 'The road',
    cast: { tier: 3 },
    req: { skill: 45, connections: 35, age: [22, 40] },
    weight: 2,
    body: (v) => `${v.artist} wants you out as musical director. Eleven months of buses and no studio time.`,
    accept: { label: 'Go out', fx: { cash: 95000, connections: 18, relevance: 10, skill: -2, taste: -3 }, diary: 'eleven months of buses. You came home with money and no ideas.' },
    pass: { label: 'Stay in the room', fx: { skill: 6, taste: 4, connections: -3 }, diary: null },
  },
  {
    id: 'c_agency_demo',
    cls: 'COMMON',
    title: 'The agency',
    req: { skill: 30, age: [20, 50] },
    weight: 3,
    body: () => 'An ad agency needs sixty seconds that sounds expensive and means nothing. They pay in two weeks.',
    accept: { label: 'Write the sixty', fx: { cash: 34000, taste: -6, relevance: -2 }, diary: 'you wrote sixty seconds that meant nothing and it paid better than anything you loved.' },
    pass: { label: 'Not this year', fx: { taste: 3 }, diary: null },
  },
  {
    id: 'c_sample_clearance',
    cls: 'COMMON',
    title: 'The clearance',
    req: { skill: 35, relevance: 15 },
    weight: 2,
    body: () => 'The best thing you made this year is built on four bars of a 1971 record. The estate wants 70% and an apology.',
    accept: { label: 'Give them the 70%', fx: { taste: 6, relevance: 6, cash: -8000, placement: { tier: 2, credit: 'the record with the 1971 sample on it' } }, diary: 'you gave the estate seventy percent and released it anyway. It was the right call and it cost you a car.' },
    pass: { label: 'Shelve it', fx: { taste: -2 }, diary: 'the best thing you made that year is still on a drive in a drawer.' },
  },
  {
    id: 'c_collaborator_flake',
    cls: 'COMMON',
    title: 'The one who flakes',
    cast: { tier: 2 },
    req: { age: [17, 40] },
    weight: 3,
    body: (v) => `${v.artist} has cancelled on you four times. The fifth session is booked and the room is paid for.`,
    accept: { label: 'Book the room again', fx: { cash: -1200, connections: 3, relevance: 2 }, diary: '{artist} cancelled a fifth time. You worked alone in a paid room and made something better.' },
    pass: { label: 'Stop answering', fx: { connections: -4, taste: 3 }, diary: null },
  },
  {
    id: 'c_hard_drive',
    cls: 'COMMON',
    title: 'The drive',
    req: { age: [16, 50] },
    weight: 2,
    body: () => 'The drive with four years of sessions on it clicks once and stops. Recovery is $1,900 and no guarantee.',
    accept: { label: 'Pay for recovery', fx: { cash: -1900, skill: 1 }, diary: 'you paid nineteen hundred dollars to get four years back and never opened most of it again.' },
    pass: { label: 'Let it go', fx: { taste: 3, skill: -2 }, diary: 'four years went with the drive. You told people it was freeing and eventually believed it.' },
  },
  {
    id: 'c_assistant',
    cls: 'COMMON',
    title: 'The kid who emails',
    req: { relevance: 30, age: [26, 50] },
    weight: 2,
    body: () => 'A nineteen-year-old has emailed you eleven times. The eleventh one has a beat attached and the beat is good.',
    accept: { label: 'Bring them in', fx: { connections: 6, skill: 2, cash: -14000, taste: 3 }, diary: 'you hired the kid who emailed eleven times. He was better than you at nineteen and you told him so.' },
    pass: { label: 'Do not reply', fx: {}, diary: null },
  },
  {
    id: 'c_studio_lease',
    cls: 'COMMON',
    title: 'A room of your own',
    req: { cash: 40000, age: [24, 46] },
    weight: 2,
    body: () => 'A room with a real console, three years on the lease. It is the amount of money you have.',
    accept: { label: 'Sign it', fx: { cash: -85000, skill: 8, taste: 6, connections: 8, flags: ['own_room'] }, diary: 'you signed a three-year lease on a room with a real console and were terrified for eleven months.' },
    pass: { label: 'Keep working from home', fx: { cash: 4000 }, diary: null },
  },
  {
    id: 'c_sync_library',
    cls: 'COMMON',
    title: 'Library music',
    req: { skill: 40, age: [24, 50] },
    weight: 3,
    body: () => 'A library wants two hundred cues. Sixty seconds each, no vocals, exclusive forever, decent money forever.',
    accept: { label: 'Write two hundred cues', fx: { cash: 62000, taste: -7, skill: 4, relevance: -4 }, diary: 'two hundred cues, sixty seconds each. Somewhere in the world one of them is playing right now under a weather report.' },
    pass: { label: 'No', fx: { taste: 3 }, diary: null },
  },
  {
    id: 'c_a_and_r_lunch',
    cls: 'COMMON',
    title: 'Lunch',
    req: { relevance: 20, connections: 20 },
    weight: 3,
    body: () => 'An A&R wants lunch. There is no specific project. There is never a specific project, and yet.',
    accept: { label: 'Take the lunch', fx: { connections: 10, relevance: 4, taste: -1 }, diary: 'the lunch was about nothing. Two years later it was about something.' },
    pass: { label: 'Skip it', fx: { skill: 3, connections: -2 }, diary: null },
  },
  {
    id: 'c_teach_class',
    cls: 'COMMON',
    title: 'The masterclass',
    req: { skill: 55, age: [28, 50] },
    weight: 2,
    body: () => 'A school will pay you to talk for two hours about how you do it. You have never had to say it out loud.',
    accept: { label: 'Teach it', fx: { cash: 9000, taste: 4, connections: 5, skill: 3 }, diary: 'explaining it out loud for two hours taught you three things about your own records.' },
    pass: { label: 'Decline', fx: {}, diary: null },
  },
  {
    id: 'c_old_beat_viral',
    cls: 'COMMON',
    title: 'Something from 2029',
    req: { age: [30, 50], relevance: 15 },
    weight: 2,
    body: () => 'A loop you made a decade ago is on forty thousand videos this month. You own none of the recording and all of the composition.',
    accept: { label: 'Chase the paperwork', fx: { cash: 41000, relevance: 9, taste: -2 }, diary: 'a loop you forgot making paid better than the year you were proud of.' },
    pass: { label: 'Let it run', fx: { taste: 2, relevance: 4 }, diary: null },
  },
  {
    id: 'c_health',
    cls: 'COMMON',
    title: 'The wrist',
    req: { age: [30, 50] },
    weight: 3,
    body: () => 'Your right hand goes numb in sessions. The doctor says the word "chronic" and then the word "rest."',
    accept: { label: 'Take the rest', fx: { relevance: -6, cash: -12000, taste: 3 }, diary: 'you took six months off for your hand and half the calendar did not come back.' },
    pass: { label: 'Work through it', fx: { skill: 2, cash: 15000 }, diary: 'you worked through it. The hand is the hand now.' },
  },
  {
    id: 'c_credit_dispute',
    cls: 'COMMON',
    title: 'The credit',
    cast: { tier: 3 },
    req: { relevance: 25 },
    weight: 2,
    body: (v) => `${v.artist}'s album came out with your production credited to somebody else. The label says it is a printing error.`,
    accept: { label: 'Fight it publicly', fx: { relevance: 6, connections: -10, taste: 2 }, diary: 'you said the word "stolen" in public and got the credit and a reputation.' },
    pass: { label: 'Let it go', fx: { connections: 8, relevance: -4 }, diary: 'you let them keep the credit. It bought you four years of phone calls and cost you the thing itself.' },
  },
  {
    id: 'c_underground_tape',
    cls: 'COMMON',
    title: 'The tape',
    cast: { track: 'underground' },
    req: { taste: 25, age: [17, 50] },
    weight: 3,
    body: (v) => `${v.artist} has forty dollars and a poem about his uncle. He wants the whole tape produced and he wants it to sound like a flooded basement.`,
    accept: { label: 'Make the tape', fx: { taste: 10, skill: 4, relevance: 2, cash: 40, connections: 3, placement: { tier: 2 }, underground: true }, diary: 'you made the whole tape for forty dollars. Three hundred people heard it and every one of them meant it.' },
    pass: { label: 'Pass', fx: { cash: 500 }, diary: null },
  },
  {
    id: 'c_underground_collective',
    cls: 'COMMON',
    title: 'The collective',
    cast: { track: 'underground' },
    req: { taste: 40, age: [19, 50] },
    weight: 3,
    body: (v) => `${v.artist} and six others share a loft and a bank account. They want you inside it, not hired by it.`,
    accept: { label: 'Move into it', fx: { taste: 14, skill: 6, connections: 10, relevance: -3, cash: -4000, placement: { tier: 2 }, underground: true, flags: ['underground_in'] }, diary: 'you stopped being a producer they hired and started being one of them.' },
    pass: { label: 'Stay outside it', fx: { relevance: 3, cash: 2000 }, diary: null },
  },
  {
    id: 'c_underground_instrumentals',
    cls: 'COMMON',
    title: 'Instrumentals',
    req: { taste: 45, skill: 40, age: [20, 50] },
    weight: 3,
    body: () => 'A small label with a distribution deal and no money wants a record of your instrumentals. Three hundred vinyl, no promotion, complete control.',
    accept: { label: 'Give them the record', fx: { taste: 12, skill: 5, relevance: 3, cash: 900, placement: { tier: 2, credit: 'your own instrumental record' }, underground: true }, diary: 'three hundred copies of your instrumentals, on vinyl, with nobody\'s name on it but yours.' },
    pass: { label: 'Not a real release', fx: { cash: 3000, taste: -2 }, diary: null },
  },
  {
    id: 'c_underground_regional',
    cls: 'COMMON',
    title: 'The regional one',
    cast: { track: 'underground' },
    req: { taste: 50, skill: 45, age: [22, 50] },
    weight: 3,
    body: (v) => `${v.artist} has been the best rapper in one city for eleven years and has never left it. He wants a record and he wants it to sound like that city.`,
    accept: { label: 'Go there and make it', fx: { taste: 15, skill: 6, relevance: 5, cash: 6000, connections: 5, placement: { tier: 3 }, underground: true }, diary: 'you went to a city you had never been to and made a record that only makes sense there, which is the point.' },
    pass: { label: 'Too far', fx: { cash: 4000 }, diary: null },
  },
  {
    id: 'c_underground_group_album',
    cls: 'COMMON',
    title: 'The house record',
    cast: { track: 'underground' },
    req: { taste: 58, flags: ['underground_in'] },
    weight: 4,
    body: (v) => `Everyone in the loft is on it, ${v.artist} loudest of all. Twenty-two tracks, one summer, no advance and no adults.`,
    accept: { label: 'Make the house record', fx: { taste: 16, skill: 6, connections: 8, relevance: 4, cash: 2000, placement: { tier: 3 }, underground: true }, diary: 'twenty-two tracks in one summer with everyone in the building on it. Nobody got paid and nobody brought it up.' },
    pass: { label: 'Take paid work instead', fx: { cash: 32000, taste: -6, connections: -6 }, diary: null },
  },
  {
    id: 'c_underground_press',
    cls: 'COMMON',
    title: 'The write-up',
    req: { taste: 55, flags: ['underground_in'] },
    weight: 2,
    body: () => 'A critic who matters to four thousand people calls your production "the most important American record nobody bought."',
    accept: { label: 'Do the interview', fx: { taste: 8, relevance: 5, connections: 5 }, diary: 'the most important American record nobody bought, he called it. You have the sentence framed and pretend you do not.' },
    pass: { label: 'Do not respond', fx: { taste: 5 }, diary: null },
  },
  {
    id: 'c_gear_gas',
    cls: 'COMMON',
    title: 'The thing on the wall',
    req: { cash: 12000, age: [20, 50] },
    weight: 2,
    body: () => 'There is a piece of outboard you have wanted since you were seventeen. It is $11,000 and it does one thing.',
    accept: { label: 'Buy it', fx: { cash: -11000, taste: 5, skill: 3 }, diary: 'you bought the thing you had wanted since seventeen and used it on everything for a year, correctly.' },
    pass: { label: 'Do not buy it', fx: { cash: 800, taste: 2 }, diary: null },
  },
  {
    id: 'c_day_job_offer',
    cls: 'COMMON',
    title: 'The salary',
    req: { age: [22, 44], cash: [-999999, 20000] },
    weight: 3,
    body: () => 'A software company needs somebody who understands audio. Ninety-five thousand, dental, a laptop that does not overheat.',
    accept: { label: 'Take the job', fx: { cash: 190000, relevance: -14, skill: -2, taste: -4, flags: ['took_salary'] }, diary: 'you took the salary. The overheating stopped, and so did some other things.' },
    pass: { label: 'Turn it down', fx: { relevance: 3, taste: 3 }, diary: 'you turned down ninety-five thousand dollars and told nobody, because saying it out loud would have made it a decision.' },
  },
  {
    id: 'c_dj_residency',
    cls: 'COMMON',
    title: 'Thursdays',
    req: { age: [19, 34], relevance: 6 },
    weight: 2,
    body: () => 'A club will give you Thursdays. Two hundred a night and everyone in the city walks through eventually.',
    accept: { label: 'Take Thursdays', fx: { cash: 9600, relevance: 9, connections: 11, skill: 1 }, diary: 'you had Thursdays for two years and met everyone you would work with for the next ten.' },
    pass: { label: 'Pass', fx: { skill: 3 }, diary: null },
  },
  {
    id: 'c_documentary_score_small',
    cls: 'COMMON',
    title: 'The documentary',
    req: { skill: 45, taste: 45, age: [24, 50] },
    weight: 2,
    body: () => 'A documentary about a closed factory needs forty minutes of music and has nine thousand dollars.',
    accept: { label: 'Score it', fx: { cash: 9000, taste: 8, skill: 5, flags: ['scored_something'] }, diary: 'forty minutes of music for a film about a closed factory. It is the first thing you made that was not about you.' },
    pass: { label: 'Pass', fx: { cash: 1000 }, diary: null },
  },
  {
    id: 'c_burnout',
    cls: 'COMMON',
    title: 'The wall',
    req: { age: [20, 50] },
    weight: 4,
    body: () => 'You have opened the same session eleven days running and moved nothing. There is a deadline Friday.',
    accept: { label: 'Push through Friday', fx: { skill: -3, taste: -4, cash: 12000, relevance: 2 }, diary: 'you delivered on Friday. You have never listened to it again.' },
    pass: { label: 'Miss the deadline', fx: { connections: -8, relevance: -5, cash: -3000 }, diary: 'you missed it. The email you sent was four lines and honest and cost you the client.' },
  },
  {
    id: 'c_lost_client',
    cls: 'COMMON',
    title: 'The one who left',
    cast: { tier: 2 },
    req: { relevance: 15 },
    weight: 3,
    body: (v) => `${v.artist} has gone to a producer eight years younger. You found out from the credits.`,
    accept: { label: 'Call and ask why', fx: { connections: 4, taste: 3, relevance: -2 }, diary: 'you called {artist} and asked why. The answer was reasonable, which was the worst part.' },
    pass: { label: 'Say nothing', fx: { relevance: -5 }, diary: 'you found out from the credits and said nothing to anybody for two weeks.' },
  },
  {
    id: 'c_festival_slot',
    cls: 'COMMON',
    title: 'The tent',
    req: { relevance: 35, age: [22, 42] },
    weight: 2,
    body: () => 'A festival wants you to play your own production set. Two in the afternoon, the second-smallest tent.',
    accept: { label: 'Play the tent', fx: { relevance: 8, connections: 6, cash: 6000 }, diary: 'two in the afternoon, second-smallest tent, four hundred people, and it was the best day of that year.' },
    pass: { label: 'Decline', fx: { taste: 2 }, diary: null },
  },
  {
    id: 'c_beat_pack_star',
    cls: 'COMMON',
    title: 'The pack',
    cast: { tier: 4 },
    req: { skill: 55, connections: 40 },
    weight: 3,
    body: (v) => `${v.artist}'s camp asks for a pack of twenty. They will keep zero or they will keep one.`,
    accept: { label: 'Send twenty', fx: { skill: 3, connections: 5, relevance: 3 }, diary: 'you sent twenty to {artist}\'s camp. They kept none, and said the drums were interesting.' },
    pass: { label: 'Send nothing', fx: { taste: 2, connections: -3 }, diary: null },
  },
  {
    id: 'c_beat_pack_hit',
    cls: 'COMMON',
    title: 'They kept one',
    cast: { tier: 4 },
    req: { skill: 60, connections: 40, relevance: 36 },
    weight: 2,
    body: (v) => `${v.artist}'s camp kept one from the pack. Nobody has told you which one and the album is out in March.`,
    accept: { label: 'Wait for March', fx: { placement: { tier: 4 }, relevance: 16, cash: 48000, connections: 8 }, diary: 'they kept one. You found out which in March, in a rental car, and had to pull over.' },
    pass: { label: 'Withdraw the pack', fx: { taste: 4, connections: -6 }, diary: null },
  },
  {
    id: 'c_mentor_dies',
    cls: 'COMMON',
    title: 'The funeral',
    req: { age: [34, 50], connections: 25 },
    weight: 2,
    body: () => 'The producer who told you the truth about four of your beats is dead at sixty-one. The service is Tuesday, four states away.',
    accept: { label: 'Go', fx: { taste: 8, connections: 6, cash: -1200 }, diary: 'you went four states for the service and stood at the back and heard three people describe your own life.' },
    pass: { label: 'Send something', fx: { taste: -2 }, diary: 'you sent flowers to a funeral four states away and worked that day instead.' },
  },
  {
    id: 'c_nephew',
    cls: 'COMMON',
    title: 'The nephew',
    req: { age: [36, 50] },
    weight: 2,
    body: () => 'Your sister\'s kid has thirty beats and no idea how bad they are. He wants you to listen to all thirty.',
    accept: { label: 'Listen to all thirty', fx: { taste: 4, skill: 1, connections: 2 }, diary: 'you listened to all thirty. Two were genuinely good and you told him which and why.' },
    pass: { label: 'Listen to three', fx: {}, diary: null },
  },
  {
    id: 'c_algorithm_shift',
    cls: 'COMMON',
    title: 'The shift',
    req: { age: [32, 50], relevance: 30 },
    weight: 3,
    body: () => 'The thing you are good at stopped being the thing. It happened over about eight months and nobody wrote it down.',
    accept: { label: 'Learn the new thing', fx: { skill: 6, relevance: 10, taste: -5 }, diary: 'you learned the new thing at thirty-nine, competently, the way you learn a language as an adult.' },
    pass: { label: 'Keep doing your thing', fx: { taste: 8, relevance: -10, skill: 3 }, diary: 'you kept doing your thing while it stopped being the thing, on purpose, with your eyes open.' },
  },
  {
    id: 'c_catalog_pitch',
    cls: 'COMMON',
    title: 'The offer on the catalog',
    req: { age: [38, 50], relevance: 25 },
    weight: 2,
    body: () => 'A fund will buy your catalog outright. It is more money than you have ever seen at once and it ends the mailbox forever.',
    accept: { label: 'Sell it', fx: (s) => ({ cash: 220000 + 9000 * s.relevance, royaltyMult: 0, taste: -6, flags: ['sold_catalog'] }), diary: 'you sold the catalog. The number was real and the mailbox went quiet the same week.' },
    pass: { label: 'Keep it', fx: { taste: 4 }, diary: null },
  },
  {
    id: 'c_reissue',
    cls: 'COMMON',
    title: 'The reissue',
    req: { age: [40, 50], taste: 55 },
    weight: 2,
    body: () => 'A label wants to reissue the record you made at twenty-six that sold four hundred copies. Vinyl, liner notes, an essay by somebody serious.',
    accept: { label: 'Let them', fx: { taste: 10, relevance: 7, cash: 8000 }, diary: 'they reissued the record that sold four hundred copies. The essay called it ahead of its time, which is what they say when nobody bought it.' },
    pass: { label: 'Leave it buried', fx: { taste: 3 }, diary: null },
  },
  {
    id: 'c_sampled_uncredited',
    cls: 'COMMON',
    title: 'Somebody younger',
    req: { age: [36, 50] },
    weight: 3,
    body: () => 'A hit this summer is built on eight bars of yours. The credit list does not have your name and the label is not returning the email.',
    accept: { label: 'Lawyer it', fx: { cash: 60000, connections: -8, relevance: 5, taste: -2 }, diary: 'you lawyered the kid who sampled you and won and felt exactly nothing.' },
    pass: { label: 'Let the kid have it', fx: { taste: 8, relevance: -2 }, diary: 'you let the kid have it. Somebody did that for you once and you never found out who.' },
  },

  {
    id: 'c_the_wall_upstairs',
    cls: 'COMMON',
    title: 'Through the floor',
    req: { age: [14, 20] },
    weight: 2,
    body: () => 'Your sister has a test Thursday and the kick is coming through the floor. Somebody has to lose this one.',
    accept: { label: 'Work in headphones for a year', fx: { skill: 5, taste: -2 }, diary: 'you mixed a whole year in headphones and it took until you were twenty-six to unlearn what that did to your low end.' },
    pass: { label: 'Keep the monitors up', fx: { skill: 7, taste: 3 }, diary: 'you kept the monitors up. The house held a vote about it and you lost the vote and kept the monitors up.' },
  },
  {
    id: 'c_the_singer',
    cls: 'COMMON',
    title: 'A voice and nothing else',
    cast: { tier: 1 },
    req: { age: [16, 34], skill: 20 },
    weight: 3,
    body: (v) => `${v.artist} has the best voice you have heard in person and no songs, no plan, and a shift at seven.`,
    accept: { label: 'Write it for them', fx: { skill: 4, taste: 7, connections: 4, relevance: 3, placement: { tier: 1 } }, diary: 'you wrote everything for {artist} and they sang it better than you imagined it, which was the first time that ever happened.' },
    pass: { label: 'You need a writer, not a producer', fx: { taste: 2 }, diary: null },
  },
  {
    id: 'c_the_flood',
    cls: 'COMMON',
    title: 'Water',
    req: { age: [18, 44] },
    weight: 2,
    body: () => 'A pipe goes in the ceiling above the room. Insurance covers the gear and not the four months.',
    accept: { label: 'Rebuild the room', fx: { cash: -9000, skill: 3, taste: 2 }, diary: 'you rebuilt the room from the floor up and the second version was better than the first in every way that mattered.' },
    pass: { label: 'Work off a laptop again', fx: { taste: 4, skill: -1, cash: 2000 }, diary: 'back to the laptop, at thirty-one, on a kitchen table, and some of it was the best work of the decade.' },
  },
  {
    id: 'c_podcast_theme',
    cls: 'COMMON',
    title: 'Forty seconds',
    req: { age: [20, 50], skill: 25 },
    weight: 3,
    body: () => 'A show with an audience wants forty seconds of theme music. It is one afternoon and it plays at the top of every episode forever.',
    accept: { label: 'Write the forty seconds', fx: { cash: 4500, relevance: 5, connections: 4, taste: -1 }, diary: 'forty seconds you wrote in an afternoon has now been heard more times than everything else you made combined.' },
    pass: { label: 'Not worth the afternoon', fx: { skill: 2 }, diary: null },
  },
  {
    id: 'c_leaked_session',
    cls: 'COMMON',
    title: 'The leak',
    cast: { tier: 3 },
    req: { relevance: 22, age: [22, 50] },
    weight: 2,
    body: (v) => `Unfinished stems from the ${v.artist} session are on a forum. Someone with your login did this and there are three people it could be.`,
    accept: { label: 'Find out which one', fx: { connections: -10, taste: 2, relevance: 4 }, diary: 'you found out which of the three it was. He apologised and you have never worked with any of them since.' },
    pass: { label: 'Change the passwords and move on', fx: { connections: 3, relevance: 2 }, diary: 'you changed every password and never asked which of the three it was, which was cheaper than knowing.' },
  },
  {
    id: 'c_the_snub',
    cls: 'COMMON',
    title: 'The list',
    req: { relevance: 35, age: [26, 50] },
    weight: 2,
    body: () => 'A magazine publishes the fifty producers who matter. You are not on it. Two people you taught are.',
    accept: { label: 'Say something about it', fx: { relevance: 6, connections: -8, taste: -3 }, diary: 'you posted about the list. It was funny, and true, and you should not have posted it.' },
    pass: { label: 'Say nothing', fx: { taste: 6 }, diary: 'two people you taught made the list and you sent them both a message saying congratulations, and meant it, mostly.' },
  },
  {
    id: 'c_payout_change',
    cls: 'COMMON',
    title: 'The new model',
    req: { age: [30, 50], relevance: 20 },
    weight: 3,
    body: () => 'The payout structure changes overnight. Everything under a thousand plays a month is now worth nothing, which is most of your catalogue.',
    accept: { label: 'Restructure everything', fx: (s) => ({ cash: 20000 + 300 * s.relevance, taste: -4, connections: 5 }), diary: 'you spent a year restructuring a catalogue around a rule somebody invented in a meeting you were not in.' },
    pass: { label: 'Let the long tail die', fx: { taste: 5, royaltyMult: 0.85 }, diary: null },
  },
  {
    id: 'c_the_parent',
    cls: 'COMMON',
    title: 'The phone call',
    req: { age: [28, 50] },
    weight: 3,
    body: () => 'Your father is in hospital four states away and it is not an emergency yet. The session is Tuesday and the artist flies out Wednesday.',
    accept: { label: 'Go', fx: { taste: 6, relevance: -6, connections: -6, cash: -6000 }, diary: 'you went. You lost the session and the artist and you would do it again exactly the same way.' },
    pass: { label: 'Take the session', fx: { relevance: 6, connections: 6, cash: 20000, taste: -4 }, diary: 'you took the session. It went well. You have never told anyone what you chose that week.' },
  },
  {
    id: 'c_the_room_next_door',
    cls: 'COMMON',
    title: 'Room B',
    req: { age: [22, 44], connections: 25 },
    weight: 2,
    body: () => 'Somebody twenty-three is in the room next door making something that is obviously better than what you are making, on a fraction of the gear.',
    accept: { label: 'Go and ask how', fx: { skill: 6, taste: 8, connections: 6 }, diary: 'you knocked on the door of room B and asked a twenty-three-year-old to explain it to you, and he did, and it changed the next ten years.' },
    pass: { label: 'Close your door', fx: { skill: 3, taste: -3 }, diary: 'you closed your door and worked louder. You could still hear it.' },
  },
  {
    id: 'c_the_anniversary',
    cls: 'COMMON',
    title: 'Ten years of it',
    req: { age: [30, 50], relevance: 18 },
    weight: 2,
    body: () => 'A record you produced turns ten. There is a show, a panel, and a room full of people being nostalgic about the worst year of your life.',
    accept: { label: 'Do the anniversary', fx: { relevance: 8, connections: 8, cash: 14000, taste: -2 }, diary: 'you stood on a stage and was nostalgic in public about the worst year of your life, for money, and it was fine.' },
    pass: { label: 'Skip it', fx: { taste: 5, relevance: -3 }, diary: null },
  },

  /* ================================================================= */
  /* CONTRACT — the real decisions. Advance now vs. points later.      */
  /* ================================================================= */
  {
    id: 'k_first_manager',
    cls: 'CONTRACT',
    title: 'Management',
    req: { age: [17, 30], relevance: 8, not: ['has_manager'] },
    weight: 4,
    body: () => 'A manager with two real clients wants twenty percent of everything, for five years, starting now. He is very good in the room.',
    accept: {
      label: 'Sign with him',
      fx: { connections: 20, relevance: 8, royaltyMult: 0.8, flags: ['has_manager', 'manager_pending'] },
      diary: 'you signed the management deal in a diner. Five years, twenty percent, and a handshake you thought about for a decade.',
    },
    pass: { label: 'Manage yourself', fx: { connections: -4, taste: 3 }, diary: 'you managed yourself. It cost you rooms and saved you a lawsuit you will never know about.' },
  },
  {
    id: 'k_publishing_advance',
    cls: 'CONTRACT',
    title: 'The advance',
    req: { age: [18, 40], skill: 35, relevance: 18, not: ['pub_deal'] },
    weight: 4,
    body: () => 'A publisher offers a real advance against your songwriting. It is recoupable, which they say quietly, and it is enough to stop worrying for four years.',
    accept: { label: 'Take the advance', fx: { cash: 120000, publishing: -50, connections: 10, flags: ['pub_deal'] }, diary: 'you took the advance and stopped worrying for four years, which is a long time to not worry.' },
    pass: { label: 'Own your publishing', fx: { taste: 4, cash: -4000 }, diary: 'you kept your publishing. It meant three lean years and one very good decade.' },
  },
  {
    id: 'k_points_vs_flat',
    cls: 'CONTRACT',
    title: 'Points or the check',
    cast: { tier: 3 },
    req: { skill: 45, connections: 25 },
    weight: 4,
    body: (v) => `${v.artist}'s label will give you forty thousand flat, or three points on the back end and nothing today.`,
    accept: { label: 'Take three points', fx: { placement: { tier: 3 }, relevance: 8, royaltyMult: 1.35, cash: 0 }, diary: 'you took points instead of the check on {artist}\'s record. For two years it looked stupid.' },
    pass: { label: 'Take the forty thousand', fx: { placement: { tier: 3 }, relevance: 8, cash: 40000, royaltyMult: 0.85 }, diary: 'you took the check. It cleared, which is more than most things do.' },
  },
  {
    id: 'k_sell_masters',
    cls: 'CONTRACT',
    title: 'The masters',
    req: { age: [18, 26], relevance: 15, not: ['sold_masters'] },
    weight: 3,
    body: () => 'The paperwork in front of you assigns your masters in perpetuity throughout the universe. There is a check attached and you are twenty-two.',
    accept: { label: 'Sign it', fx: { cash: 55000, relevance: 10, royaltyMult: 0.25, flags: ['sold_masters'] }, diary: 'you signed away the masters in perpetuity throughout the universe. You were twenty-two and the check was real.' },
    pass: { label: 'Have someone read it', fx: { cash: -2500, taste: 5, connections: -3 }, diary: 'you paid a lawyer twenty-five hundred dollars to read it and she told you not to sign it and you did not.' },
  },
  {
    id: 'k_360',
    cls: 'CONTRACT',
    title: 'The 360',
    req: { relevance: 30, connections: 25, age: [20, 38] },
    weight: 3,
    body: () => 'A label wants you as a signed producer. Salary, a room, a budget — and a piece of everything you touch for the term, including what you make on weekends.',
    accept: { label: 'Sign the term', fx: { cash: 150000, relevance: 14, connections: 14, royaltyMult: 0.55, taste: -4, flags: ['label_deal'] }, diary: 'they gave you a room, a budget, and a piece of everything you touched, including the weekends.' },
    pass: { label: 'Stay independent', fx: { taste: 6, connections: -5 }, diary: null },
  },
  {
    id: 'k_ghost_nda',
    cls: 'CONTRACT',
    title: 'The NDA',
    cast: { tier: 5 },
    req: { skill: 65, connections: 50 },
    weight: 3,
    body: (v) => `${v.artist} needs three songs finished and needs your name to never appear anywhere, ever, under penalty of a number with six figures in it.`,
    accept: { label: 'Sign the NDA', fx: { cash: 320000, skill: 6, connections: 12, relevance: 0, taste: 2, flags: ['ghost'] }, diary: 'you finished three songs for the biggest artist alive and cannot say so, and will not, ever.' },
    pass: { label: 'Refuse to be invisible', fx: { taste: 5, connections: -8, relevance: 2 }, diary: null },
  },
  {
    id: 'k_admin_switch',
    cls: 'CONTRACT',
    title: 'Administration',
    req: { flags: ['pub_deal'], age: [26, 46] },
    weight: 2,
    body: () => 'You can buy your way out of the publishing deal. It costs most of what you have and returns the half of yourself you sold at twenty-four.',
    accept: { label: 'Buy back in', fx: { cash: -140000, publishing: 45, taste: 6, royaltyMult: 1.4, clearFlags: ['pub_deal'] }, diary: 'you bought your publishing back and were broke and correct.' },
    pass: { label: 'Leave it', fx: { cash: 12000 }, diary: null },
  },
  {
    id: 'k_coprod_split',
    cls: 'CONTRACT',
    title: 'The split sheet',
    cast: { tier: 3 },
    req: { skill: 50, relevance: 25 },
    weight: 3,
    body: (v) => `You built the whole thing. Somebody who was in the room for forty minutes wants half, and he is the reason ${v.artist} is on it.`,
    accept: { label: 'Give him half', fx: { placement: { tier: 3 }, relevance: 10, connections: 12, cash: 18000, taste: -3 }, diary: 'you gave away half of the best song you had written to the man who made the phone call. It was worth it and it still stings.' },
    pass: { label: 'Refuse the split', fx: { taste: 6, connections: -14, relevance: -4 }, diary: 'you refused the split and the song came out with somebody else\'s beat on it.' },
  },
  {
    id: 'k_sync_exclusive',
    cls: 'CONTRACT',
    title: 'Exclusive sync',
    req: { skill: 45, age: [26, 50] },
    weight: 2,
    body: () => 'A sync agency wants exclusivity on your whole catalog for six years. They are very good and you will never place anything yourself again.',
    accept: { label: 'Give them everything', fx: { cash: 90000, royaltyMult: 1.25, relevance: -5, connections: -6 }, diary: 'you handed the catalog to the agency and stopped having to think about it, which was the point and the problem.' },
    pass: { label: 'Keep it in-house', fx: { taste: 3, connections: 4 }, diary: null },
  },
  {
    id: 'k_equity_studio',
    cls: 'CONTRACT',
    title: 'A piece of the building',
    req: { cash: 90000, connections: 40, age: [28, 48] },
    weight: 2,
    body: () => 'The room you have worked in for six years is for sale. You could own a third of it and everything that happens inside it.',
    accept: { label: 'Buy a third', fx: { cash: -160000, connections: 18, relevance: 6, flags: ['owns_studio'] }, diary: 'you bought a third of the building and started making money while you slept, which felt like cheating and was not.' },
    pass: { label: 'Stay a tenant', fx: { cash: 6000 }, diary: null },
  },
  {
    id: 'k_manager_revealed_good',
    cls: 'CONTRACT',
    title: 'Six years later',
    req: { flags: ['manager_reveal_good'], not: ['manager_resolved'] },
    weight: 9,
    body: () => 'The accountant finishes the audit of your management. Every number is where it should be. He never once took what he could have taken.',
    accept: { label: 'Extend the deal', fx: { connections: 16, relevance: 8, royaltyMult: 1.15, flags: ['manager_resolved'] }, diary: 'the audit came back clean to the dollar. You extended for another five and meant the handshake this time.' },
    pass: { label: 'Part ways anyway', fx: { connections: -6, cash: 20000, flags: ['manager_resolved'] }, diary: null },
  },
  {
    id: 'k_manager_revealed_bad',
    cls: 'CONTRACT',
    title: 'The audit',
    req: { flags: ['manager_reveal_bad'], not: ['manager_resolved'] },
    weight: 9,
    body: () => 'The accountant finishes the audit. Six years of statements, and a number missing from them that has a house in it.',
    accept: { label: 'Sue him', fx: { cash: 40000, connections: -18, relevance: -4, taste: 2, flags: ['manager_resolved', 'sued_manager'] }, diary: 'you sued the man who signed you in a diner and got back about a third of it, four years later.' },
    pass: { label: 'Walk away quietly', fx: { connections: -6, taste: 4, flags: ['manager_resolved'] }, diary: 'you walked away and never said his name in public. People assume you are still friends.' },
  },
  {
    id: 'k_recoupment',
    cls: 'CONTRACT',
    title: 'Unrecouped',
    req: { flags: ['pub_deal'], age: [26, 50], cash: [-999999, 60000] },
    weight: 2,
    body: () => 'The statement says you are unrecouped by an amount that took four years to accumulate and will take eleven to erase.',
    accept: { label: 'Sign the extension', fx: { cash: 70000, publishing: -15, taste: -3 }, diary: 'you signed the extension because the alternative was a number with a minus in front of it.' },
    pass: { label: 'Ride it out', fx: { taste: 5, cash: -8000 }, diary: null },
  },
  {
    id: 'k_brand_deal',
    cls: 'CONTRACT',
    title: 'The brand',
    req: { relevance: 45, age: [24, 48] },
    weight: 3,
    body: () => 'A shoe company wants your name on a campaign and your sound in it. It is two days of work and a great deal of money and a permanent association.',
    accept: { label: 'Take it', fx: { cash: 180000, relevance: 12, taste: -10, connections: 6 }, diary: 'your name went on a campaign. For about a year, people who did not know your records knew your face.' },
    pass: { label: 'Decline', fx: { taste: 7, relevance: -3 }, diary: null },
  },
  {
    id: 'k_own_label',
    cls: 'CONTRACT',
    title: 'Your own imprint',
    req: { cash: 120000, connections: 50, taste: 45, age: [28, 48] },
    weight: 2,
    body: () => 'You could start the label. Four artists, three years of runway, and every problem becomes yours including the ones about money.',
    accept: { label: 'Start it', fx: { cash: -200000, connections: 22, taste: 10, relevance: 10, flags: ['has_label'] }, diary: 'you started the imprint with three years of runway and signed four people who had been told no by everyone.' },
    pass: { label: 'Not your job', fx: { cash: 15000 }, diary: null },
  },

  /* ================================================================= */
  /* RARE — two-dimensional gates. The good years.                     */
  /* ================================================================= */
  {
    id: 'r_album_cycle_3',
    cls: 'RARE',
    title: 'The whole album',
    cast: { tier: 3 },
    req: { skill: 55, taste: 45, connections: 35 },
    weight: 3,
    body: (v) => `${v.artist} wants you to produce the entire record. Not tracks. The record. Fourteen months, one voice, your name on all of it.`,
    accept: { label: 'Produce the record', fx: { placement: { tier: 3 }, relevance: 16, taste: 8, skill: 6, cash: 85000, flags: ['album_credit'] }, diary: 'fourteen months on {artist}\'s record. It is the first thing with your name on all of it.' },
    pass: { label: 'Too much of your life', fx: { relevance: -4 }, diary: null },
  },
  {
    id: 'r_album_cycle_4',
    cls: 'RARE',
    title: 'An arena record',
    cast: { tier: 4 },
    req: { skill: 64, taste: 52, connections: 46, relevance: 42 },
    weight: 3,
    body: (v) => `${v.artist} sells out arenas and has never made a good album. They want you to fix that and they will not like the process.`,
    accept: { label: 'Take the record', fx: { placement: { tier: 4 }, relevance: 22, taste: 10, cash: 260000, skill: 4, flags: ['album_credit'] }, diary: 'you made {artist} an album that was actually good. It sold less than the bad ones and they never called again.' },
    pass: { label: 'Pass', fx: { taste: 3, connections: -6 }, diary: null },
  },
  {
    id: 'r_festival_main',
    cls: 'RARE',
    title: 'Main stage',
    req: { relevance: 55, connections: 45, age: [24, 44] },
    weight: 2,
    body: () => 'Main stage, eight o\'clock, your name on the poster in the size they use for people who sell tickets. Ninety minutes of your own material.',
    accept: { label: 'Take the slot', fx: { relevance: 20, cash: 120000, connections: 10, taste: -2 }, diary: 'eight o\'clock, main stage, your name in the big font. You could not see the back of it.' },
    pass: { label: 'You are not a performer', fx: { taste: 5, relevance: -5 }, diary: null },
  },
  {
    id: 'r_scoring_debut',
    cls: 'RARE',
    title: 'The first picture',
    cast: { track: 'director' },
    req: { skill: 60, taste: 60, not: ['score_track'] },
    weight: 3,
    body: (v) => `${v.artist} has an eleven-million-dollar feature and a music budget that assumes you have done this before. You have not.`,
    accept: { label: 'Say you have', fx: { placement: { tier: 3 }, score: true, taste: 12, skill: 10, cash: 110000, relevance: 6, flags: ['score_track'] }, diary: 'you told {artist} you had scored a feature before. You learned to conduct in eleven weeks.' },
    pass: { label: 'Be honest', fx: { taste: 4, connections: 4 }, diary: 'you told the truth about never having scored a picture and were not asked again for nine years.' },
  },
  {
    id: 'r_tv_score',
    cls: 'RARE',
    title: 'Eight episodes',
    req: { flags: ['score_track'], skill: 65, taste: 60 },
    weight: 2,
    body: () => 'A prestige limited series. Eight episodes, forty minutes of music each, delivered while they are still shooting.',
    accept: { label: 'Take the series', fx: { placement: { tier: 4, credit: 'the limited series' }, score: true, tv: true, cash: 300000, taste: 8, skill: 6, relevance: 8 }, diary: 'eight episodes in fourteen months. You wrote the main title nineteen times and they used the second one.' },
    pass: { label: 'Not while shooting', fx: { taste: 3 }, diary: null },
  },
  {
    id: 'r_grammy_campaign',
    cls: 'RARE',
    title: 'The campaign',
    req: { taste: 60, relevance: 45, connections: 45 },
    weight: 2,
    body: () => 'The label will spend real money campaigning your production credit. It is dinners, it is voters, it is a season of pretending it is about the music.',
    accept: { label: 'Do the campaign', fx: { relevance: 12, connections: 10, taste: -4, flags: ['campaigning'] }, diary: 'you spent a season at dinners with people who vote, and hated exactly nine percent of it.' },
    pass: { label: 'Let the work stand', fx: { taste: 8, relevance: -3 }, diary: null },
  },
  {
    id: 'r_uk_camp',
    cls: 'RARE',
    title: 'Across the water',
    cast: { tier: 3, region: 'UK' },
    req: { status: 3, skill: 50, connections: 35 },
    weight: 3,
    body: (v) => `A label in London flies you over for ${v.artist}. Different room, different rules, and they mix everything louder.`,
    accept: { label: 'Fly over', fx: { placement: { tier: 3 }, relevance: 12, connections: 10, skill: 4, cash: 45000, flags: ['intl_uk'] }, diary: 'London for six weeks with {artist}. You came back with a different idea of what loud means.' },
    pass: { label: 'Stay in the States', fx: { cash: 3000 }, diary: null },
  },
  {
    id: 'r_de_techno',
    cls: 'RARE',
    title: 'Berlin',
    cast: { tier: 3, region: 'DE' },
    req: { status: 4, skill: 55, taste: 50 },
    weight: 2,
    body: (v) => `${v.artist} wants three tracks and does not care about your American drums. The session starts at midnight and ends when it ends.`,
    accept: { label: 'Go to Berlin', fx: { placement: { tier: 3 }, relevance: 12, taste: 10, skill: 5, cash: 30000, flags: ['intl_de'] }, diary: 'three tracks in Berlin with {artist}, all of them started after midnight, none of them in a key.' },
    pass: { label: 'Decline', fx: { cash: 2000 }, diary: null },
  },
  {
    id: 'r_fr_pop',
    cls: 'RARE',
    title: 'Paris',
    cast: { tier: 3, region: 'FR' },
    req: { status: 4, taste: 55, connections: 40 },
    weight: 2,
    body: (v) => `${v.artist} wants an American producer and a French record, in that order, and will fight you about which is which.`,
    accept: { label: 'Take it', fx: { placement: { tier: 3 }, relevance: 11, taste: 9, cash: 52000, flags: ['intl_fr'] }, diary: 'you argued with {artist} in two languages for five months and made something neither of you would have alone.' },
    pass: { label: 'Pass', fx: { cash: 2000 }, diary: null },
  },
  {
    id: 'r_ca_star',
    cls: 'RARE',
    title: 'Toronto',
    cast: { tier: 4, region: 'CA' },
    req: { status: 4, skill: 60, relevance: 45 },
    weight: 2,
    body: (v) => `${v.artist} keeps a room in Toronto and works from eleven at night. The camp is small and permanent and you are being invited in.`,
    accept: { label: 'Join the camp', fx: { placement: { tier: 4 }, relevance: 16, connections: 14, cash: 150000, flags: ['intl_ca'] }, diary: 'you joined a camp of six people in Toronto and worked nights for three years and never once saw daylight in that building.' },
    pass: { label: 'Stay solo', fx: { taste: 5, connections: -5 }, diary: null },
  },
  {
    id: 'r_ng_afrobeats',
    cls: 'RARE',
    title: 'Lagos',
    cast: { tier: 4, region: 'NG' },
    req: { status: 5, skill: 62, taste: 55 },
    weight: 3,
    body: (v) => `${v.artist}'s people fly you to Lagos. The rhythm section will be in the room, all of it, and they will not wait for you to catch up.`,
    accept: { label: 'Go to Lagos', fx: { placement: { tier: 4 }, relevance: 20, taste: 12, skill: 8, cash: 130000, flags: ['intl_ng'] }, diary: 'Lagos, eleven players in the room, and you spent the first two days just writing down what they were already doing.' },
    pass: { label: 'Decline', fx: { cash: 2000 }, diary: null },
  },
  {
    id: 'r_kr_camp',
    cls: 'RARE',
    title: 'Seoul',
    cast: { tier: 4, region: 'KR' },
    req: { status: 5, skill: 65, connections: 50 },
    weight: 3,
    body: (v) => `${v.artist}'s company runs the most organized writing operation you have ever seen. Forty producers, one week, four songs make it.`,
    accept: { label: 'Go to Seoul', fx: { placement: { tier: 4 }, relevance: 20, skill: 8, cash: 175000, connections: 10, taste: -2, flags: ['intl_kr'] }, diary: 'forty producers, one week, four songs. Yours was one of the four and you still do not know why.' },
    pass: { label: 'Decline', fx: { cash: 2000 }, diary: null },
  },
  {
    id: 'r_br_baile',
    cls: 'RARE',
    title: 'São Paulo',
    cast: { tier: 4, region: 'BR' },
    req: { status: 5, taste: 60, relevance: 55 },
    weight: 2,
    body: (v) => `${v.artist} wants you on a record that is going to be enormous in a country where nobody has heard of you.`,
    accept: { label: 'Take it', fx: { placement: { tier: 4 }, relevance: 18, taste: 10, cash: 90000, flags: ['intl_br'] }, diary: 'the record was enormous in a country where nobody knows your name, which turned out to be the best kind of famous.' },
    pass: { label: 'Pass', fx: { cash: 2000 }, diary: null },
  },
  {
    id: 'r_pr_urbano',
    cls: 'RARE',
    title: 'San Juan',
    cast: { tier: 4, region: 'PR' },
    req: { status: 5, skill: 65, relevance: 55 },
    weight: 2,
    body: (v) => `${v.artist}'s team gives you eleven days in San Juan and a very clear brief: do not make it sound American.`,
    accept: { label: 'Eleven days', fx: { placement: { tier: 4 }, relevance: 19, skill: 6, taste: 6, cash: 145000, flags: ['intl_pr'] }, diary: 'eleven days in San Juan, and the brief was: do not make it sound like you. So you did not, and it worked.' },
    pass: { label: 'Pass', fx: { cash: 2000 }, diary: null },
  },
  {
    id: 'r_legacy_comeback',
    cls: 'RARE',
    title: 'The comeback',
    cast: { tier: 4 },
    req: { taste: 65, skill: 60, connections: 45, age: [30, 50] },
    weight: 2,
    body: (v) => `${v.artist} has not made anything anyone liked in fifteen years and has decided that is your problem now.`,
    accept: { label: 'Take the comeback', fx: { placement: { tier: 4 }, relevance: 15, taste: 14, skill: 4, cash: 95000, flags: ['album_credit'] }, diary: 'you gave {artist} the best reviews of their life at fifty-eight. They thanked everyone but you in the press.' },
    pass: { label: 'Pass', fx: {}, diary: null },
  },
  {
    id: 'r_own_record',
    cls: 'RARE',
    title: 'Your own record',
    req: { taste: 65, skill: 60, age: [26, 50] },
    weight: 3,
    body: () => 'No artist. No brief. Your name on the front, which you have never done and have thought about every year since you were sixteen.',
    accept: { label: 'Make it', fx: { placement: { tier: 3, credit: 'your own record' }, taste: 16, skill: 8, relevance: 8, cash: -20000, flags: ['own_record'] }, diary: 'you made a record with your name on the front. It did not sell and it is the one you would keep.' },
    pass: { label: 'Not yet', fx: { cash: 8000, taste: -2 }, diary: 'you put your own record off again. There is a folder called ALBUM with three hundred and forty things in it.' },
  },
  {
    id: 'r_underground_classic',
    cls: 'RARE',
    title: 'The one they will talk about',
    cast: { track: 'underground' },
    req: { taste: 70, skill: 55, flags: ['underground_in'] },
    weight: 4,
    body: (v) => `${v.artist} has one record left in him and wants you to produce all of it. There is no budget, no label, and no reason except that it will be good.`,
    accept: { label: 'Produce all of it', fx: { placement: { tier: 4 }, underground: true, taste: 22, skill: 8, relevance: 4, cash: 1500, flags: ['underground_classic'] }, diary: 'you and {artist} made the record with no budget and no label. People will be arguing about it in twenty years.' },
    pass: { label: 'You need to eat', fx: { cash: 20000, taste: -8 }, diary: null },
  },
  {
    id: 'r_signature_gear',
    cls: 'RARE',
    title: 'Your name on the box',
    req: { relevance: 50, skill: 70, age: [30, 50] },
    weight: 2,
    body: () => 'A manufacturer wants to build a piece of hardware around the way you work and put your name on the front of it.',
    accept: { label: 'Build it with them', fx: { cash: 210000, relevance: 10, skill: 4, taste: -3 }, diary: 'there is a box with your name on it in a lot of bedrooms now. That is a stranger thing than it sounds.' },
    pass: { label: 'Decline', fx: { taste: 4 }, diary: null },
  },
  {
    id: 'r_documentary_subject',
    cls: 'RARE',
    title: 'The film about you',
    req: { relevance: 60, taste: 55, age: [34, 50] },
    weight: 2,
    body: () => 'Someone wants to make a documentary about your run. They want the studio, the family, the part in the middle you do not talk about.',
    accept: { label: 'Let them film it', fx: { relevance: 14, connections: 8, taste: -2, cash: 40000 }, diary: 'they filmed all of it, including the part in the middle. Your mother watched it twice.' },
    pass: { label: 'No cameras', fx: { taste: 6, relevance: -4 }, diary: null },
  },
  {
    id: 'r_protege',
    cls: 'RARE',
    title: 'The one you found',
    cast: { tier: 2 },
    req: { connections: 55, taste: 60, age: [32, 50] },
    weight: 2,
    body: (v) => `You found ${v.artist} first. Everyone will find them in about eighteen months. You could develop them properly or hand them over now for a fee.`,
    accept: { label: 'Develop them', fx: { placement: { tier: 4 }, relevance: 18, taste: 10, connections: 12, cash: 60000 }, diary: 'you found {artist} eighteen months before everyone else and stayed for the whole thing.' },
    pass: { label: 'Hand them over', fx: { cash: 120000, connections: 6, taste: -6, relevance: 4 }, diary: null },
  },

  /* ================================================================= */
  /* WHITE WHALE — once per account. Extremely high gates.             */
  /* ================================================================= */
  {
    id: 'w_studio_visit',
    cls: 'WHALE',
    title: 'Three in the morning',
    cast: { tier: 5 },
    req: { connections: 70, relevance: 60 },
    body: (v) => `A car is outside. ${v.artist} is in a room across town and somebody said your name. They are awake now and they will not be awake tomorrow.`,
    accept: { label: 'Get in the car', fx: { placement: { tier: 5 }, relevance: 26, connections: 18, skill: 6, cash: 240000, flags: ['whale_studio_visit'] }, diary: 'a car came at three in the morning and by six you had made something with {artist} that outlived everything else you did.' },
    pass: { label: 'Go back to sleep', fx: { taste: 4, connections: -10 }, diary: 'the car came at three in the morning and you did not get in it. You have replayed that decision for twenty years.' },
  },
  {
    id: 'w_film_score',
    cls: 'WHALE',
    title: 'No temp music',
    cast: { track: 'director' },
    req: { taste: 80, skill: 75 },
    body: (v) => `${v.artist}'s next feature. No temp music, no notes, no committee. They have seen one thing you made and they want the person who made it.`,
    accept: { label: 'Score the picture', fx: { placement: { tier: 5 }, score: true, taste: 20, skill: 12, relevance: 16, cash: 480000, flags: ['score_track', 'whale_film_score'] }, diary: 'no temp music, no notes. {artist} used your first pass for the last nine minutes of the film and did not cut a frame of it.' },
    pass: { label: 'You are not a composer', fx: { taste: 6 }, diary: 'you told {artist} you were not a composer. You were, and you knew it, and you said it anyway.' },
  },
  {
    id: 'w_dying_legend',
    cls: 'WHALE',
    title: 'The last record',
    cast: { tier: 5 },
    req: { taste: 72, connections: 55, age: [28, 50] },
    body: (v) => `${v.artist} is very ill and has eleven songs left. The sessions will be short, and there will not be many of them, and you will be the last producer they work with.`,
    accept: { label: 'Make the last one', fx: { placement: { tier: 5 }, taste: 26, skill: 8, relevance: 18, cash: 90000, flags: ['whale_dying_legend', 'album_credit'] }, diary: 'you made {artist}\'s last record in four-hour days. On the final one they held your hand and said thank you and that was the end of it.' },
    pass: { label: 'You cannot carry that', fx: { taste: 4, connections: -8 }, diary: null },
  },
  {
    id: 'w_rival',
    cls: 'WHALE',
    title: 'The one you came up with',
    cast: { tier: 4 },
    req: { relevance: 45, skill: 60, age: [28, 50] },
    body: (v) => `The producer you started with — same basement, same summer — is three floors above you now. He has ${v.artist} for eleven weeks and wants a co-production, and both of you know exactly what that means.`,
    accept: { label: 'Take the co-production', fx: { placement: { tier: 4 }, relevance: 20, connections: 16, cash: 200000, taste: -4, flags: ['whale_rival', 'ceiling_capped'] }, diary: 'you took the co-production with the man from that same basement. Everything after that was described as his, with you in the second sentence.' },
    pass: { label: 'Refuse him', fx: { taste: 10, connections: -18, relevance: -4, flags: ['whale_rival_refused'] }, diary: 'you told him no. The two of you have not spoken since and you are still not sorry.' },
  },
  {
    id: 'w_reunion',
    cls: 'WHALE',
    title: 'They remembered',
    cast: { tier: 5 },
    req: { flags: ['early_collab'], age: [34, 50], connections: 55, relevance: 35 },
    body: (v) => `The kid you made a beat for at sixteen is ${v.artist} now. Eleven years of nothing, and then a message with no preamble: still got that folder?`,
    accept: { label: 'Still got the folder', fx: { placement: { tier: 5 }, relevance: 28, taste: 14, connections: 20, cash: 350000, flags: ['whale_reunion'] }, diary: 'still got that folder, they asked. You did. You had never deleted anything, and that turned out to be the whole career.' },
    pass: { label: 'That was a long time ago', fx: { taste: 6, relevance: -6 }, diary: 'they remembered you and you told them it was a long time ago. It was the last message.' },
  },
  {
    id: 'w_defining_album',
    cls: 'WHALE',
    title: 'The one they will name',
    cast: { tier: 5 },
    req: { skill: 72, taste: 70, relevance: 66, connections: 50 },
    body: (v) => `${v.artist} has cleared eighteen months and wants one producer for the entire record. Whatever this is, it is what your name will mean afterwards.`,
    accept: { label: 'Eighteen months', fx: { placement: { tier: 5 }, relevance: 30, taste: 16, skill: 8, cash: 700000, flags: ['whale_defining_album', 'album_credit', 'defining_album'] }, diary: 'eighteen months, one voice, one producer. When people say your name now they are saying the name of that record.' },
    pass: { label: 'You are not ready', fx: { taste: 8, relevance: -8 }, diary: null },
  },
  {
    id: 'w_the_vault',
    cls: 'WHALE',
    title: 'The vault',
    cast: { tier: 5 },
    req: { taste: 74, skill: 68, connections: 48 },
    body: (v) => `${v.artist}'s estate has four hundred hours of unfinished tape and has decided you are the person to finish it. Half the world will say it should have stayed in the box.`,
    accept: { label: 'Open the box', fx: { placement: { tier: 5 }, taste: 18, skill: 10, relevance: 22, cash: 400000, flags: ['whale_vault'] }, diary: 'four hundred hours of a dead man\'s tape, and you finished eleven songs of it. Half the reviews said you should not have.' },
    pass: { label: 'Leave it in the box', fx: { taste: 14, connections: -6 }, diary: 'you told the estate the tape should stay in the box. Somebody else opened it two years later and they were right to hate it.' },
  },
  {
    id: 'w_the_chair',
    cls: 'WHALE',
    title: 'The chair',
    req: { connections: 75, relevance: 65, age: [36, 50] },
    body: () => 'A major offers you the chair. Head of the whole thing. You would decide what gets made for four years and you would not make any of it yourself.',
    accept: { label: 'Take the chair', fx: { cash: 1400000, connections: 25, relevance: 14, taste: -12, skill: -8, flags: ['whale_chair', 'ceiling_capped'] }, diary: 'you took the chair. For four years you decided what got made and did not make one single thing.' },
    pass: { label: 'Stay behind the desk', fx: { taste: 12, skill: 4, connections: -10 }, diary: 'they offered you the whole building and you said you would rather stay behind the desk, and meant it.' },
  },
];

export const WHALE_IDS = CARDS.filter((c) => c.cls === 'WHALE').map((c) => c.id);
export const WHALE_TITLES = Object.fromEntries(CARDS.filter((c) => c.cls === 'WHALE').map((c) => [c.id, c.title]));
